### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by saimaheshtaduri** [samipak458/Simple-Library-Managment#55] opened 2022-10-04 09:55 UTC
As new features and functionalities have come, I think the readme should be updated too

**Comment by samipak458** [comment] 2022-10-04 10:30
Thanks for creating an issue @saimaheshtaduri. Go ahead.

**Comment by koder-aritra** [comment] 2022-10-08 08:30
I would like to work on this issue.Can you assign it to me?

**Comment by samipak458** [comment] 2022-10-10 18:14
@koder-aritra I will assign you tomorrow if @saimaheshtaduri not reply.

@saimaheshtaduri are you working on this issue or not?

**Comment by saimaheshtaduri** [comment] 2022-10-10 18:16
yes,I am. I will raise pr by tomorrow

**Comment by jyotika6221** [comment] 2022-10-15 19:49
If the issue is not resolved yet, plz assign me this task.

**Comment by theshubhamgour** [comment] 2022-10-22 02:59
I would like to work on this issue.Can you assign it to me? @samipak458

**Comment by samipak458** [comment] 2022-10-22 06:56
Ok @saimaheshtaduri

**Comment by samipak458** [comment] 2022-10-22 06:57
@theshubhamgour and @jyotika6221 @saimaheshtaduri is already working on it. You guys can contribute to web storage.md or Azure static web app.md.

**Comment by theshubhamgour** [comment] 2022-10-22 08:40
@samipak458 Please help with the directory link where we need to update the readme.md files

**Comment by samipak458** [comment] 2022-10-22 08:44
@theshubhamgour Here are the links:
[Azure Static Web Apps](https://github.com/samipak458/Simple-Library-Managment/blob/main/Azure%20Static%20Web%20Apps.md)
[Web Storage](https://github.com/samipak458/Simple-Library-Managment/blob/main/Web%20Storage.md)

**Closed as completed** 2022-10-22 17:58 UTC
Labels: documentation, hacktoberfest
